ngorgeous/applications/destinos/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from . import views

app_name="destinos_app"

urlpatterns = [
    #url para formulario de contacto
    url(r'^visita-lugares-en-cusco-arequipa-puno-y-todo-el-peru/$',
        views.DestinationListView.as_view(),
        name='destinos_index'
    ),
    #url para ver el detalle de un destino
    url(r'^destinos/(?P<city>[-\w]+)/(?P<slug>[-\w]+)/$',
        views.DestinationDetailView.as_view(),
        name='destinos_detail'
    ),
]

ngorgeous/applications/experiencias/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from . import views

app_name="experiencias_app"

urlpatterns = [
    #url para formulario de contacto
    url(r'^viaje-por-el-peru-con-experiencias-inolvidables/$',
        views.ExperienceListView.as_view(),
        name='experiencias_index'
    ),
    #url para ver el detalle de un destino
    url(r'^viajes-por-peru/(?P<slug>[-\w]+)/(?P<pk>\d+)/$',
        views.ExperienceDetailView.as_view(),
        name='experiencias_detail'
    ),
]

ngorgeous/applications/home/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from . import views

app_name="home_app"

urlpatterns = [
    #url para formulario de contacto
    url(r'^$',
        views.HomeView.as_view(),
        name='index'
    ),
    #url para formulario de contacto
    url(r'^envia-dudas-sobre-city-tours-peru/$',
        views.ContactCreateView.as_view(),
        name='contacto'
    ),
]

ngorgeous/applications/paquetes/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from . import views

app_name="paquetes_app"

urlpatterns = [
    #url para formulario de contacto
    url(r'^tours-y-paquetes-turisticos-por-cusco-puno-arequipa-peru/$',
        views.FilterPackageView.as_view(),
        name='paquetes_list'
    ),
    #url para ver el detalle de un tour
    url(r'^(?P<city>[-\w]+)/(?P<slug>[-\w]+)/$',
        views.PackageDetailView.as_view(),
        name='paquetes-detail'
    ),
]

ngorgeous/ngorgeous/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
#
#from django.contrib.sitemaps.views import sitemap

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #
    url(r'^', include('applications.home.urls')),
    #urls para aplicacion paquetes
    url(r'^', include('applications.paquetes.urls')),
    #urls para aplicacion destinos
    url(r'^', include('applications.destinos.urls')),
    #urls para aplicacion experiecnias
    url(r'^', include('applications.experiencias.urls')),
    #url for ckeditor
    url(r'^froala_editor/', include('froala_editor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ngorgeous/templates/include/footer.html
<div class="footer">
  <a href="https://www.facebook.com/gorgeousandes" class="footer__phone">Phone: (+51)953767677 - (+51)984736476</a>
  <a href="https://www.facebook.com/gorgeousmachupicchu/" class="footer__icon"><i class="fa fa-facebook-official" aria-hidden="true"></i></a>
  <a href="https://www.facebook.com/MariellaQLopez" class="footer__icon"><i class="fa fa-youtube" aria-hidden="true"></i></a>
  <a href="https://www.instagram.com/gorgeousandes/?hl=es" class="footer__icon"><i class="fa fa-instagram" aria-hidden="true"></i></a>
  <a href="https://www.facebook.com/gorgeousandes" class="footer__icon"><i class="fa fa-google-plus-official" aria-hidden="true"></i></a>
</div>

ngorgeous/templates/include/header.html
{% load  staticfiles %}

<header>
  <div class="mov-header">
    <div class="mov-header__menu_icon">
      <i id="togle-menu" class="fa fa-bars" aria-hidden="true"></i>
    </div>
    <div class="mov-header__logo">
      <a href="#" class="mov-header__logo__link"><i class="fa fa-bus" aria-hidden="true"></i></a>
    </div>
  </div>
  <div id="nav-menu" class="mov-header-menu-enabled">
    <ul class="mov-header-menu__ul">
      <li class="mov-header-menu__ul__li__logo">
        <a href="/" class="mov-header-menu__ul__li__logo__a">GorgeousMachupicchu</a>
      </li>
      <li class="mov-header-menu__ul__li">
        <a href="/" class="mov-header-menu__ul__li__a">Home</a>
      </li>
      <li class="mov-header-menu__ul__li">
        <a href="{% url 'paquetes_app:paquetes_list' %}" class="mov-header-menu__ul__li__a">Tours</a>
      </li>
      <li class="mov-header-menu__ul__li">
        <a href="{% url 'destinos_app:destinos_index' %}" class="mov-header-menu__ul__li__a">Destinos</a>
      </li>
      <li class="mov-header-menu__ul__li">
        <a href="{% url 'experiencias_app:experiencias_index' %}" class="mov-header-menu__ul__li__a">Experiencias</a>
      </li>
      <li class="mov-header-menu__ul__li">
        <a href="{% url 'home_app:contacto' %}" class="mov-header-menu__ul__li__a">Contactanos</a>
      </li>
      <li class="mov-header-menu__ul__li">
        <a href="{% url 'paquetes_app:paquetes_list' %}" class="mov-header-menu__ul__li__a">Paquetes Turisticos</a>
      </li>
  </div>
  <!-- header for viewport pc -->
  <div class="main-header">
    <a href="/">
      <img src="{% static 'img/logo_g3.png' %}" alt="machu picchu" class="main-header__logo">
    </a>
    <ul class="main-header__menu">
      <li class="main-header__menu__li">
        <a href="/" class="main-header__menu__li__a">Home</a>
      </li>
      <li class="main-header__menu__li">
        <a href="{% url 'paquetes_app:paquetes_list' %}" class="main-header__menu__li__a">Tours</a>
      </li>
      <li class="main-header__menu__li">
        <a href="{% url 'destinos_app:destinos_index' %}" class="main-header__menu__li__a">Destinos</a>
      </li>
      <li class="main-header__menu__li">
        <a href="{% url 'experiencias_app:experiencias_index' %}" class="main-header__menu__li__a">Experiencias</a>
      </li>
      <li class="main-header__menu__li">
        <a href="{% url 'home_app:contacto' %}" class="main-header__menu__li__a">Contactanos</a>
      </li>
      <li class="main-header__menu__li">
        <a href="{% url 'paquetes_app:paquetes_list' %}" class="main-header__menu__li__a li_action">Paquetes Turisticos</a>
      </li>
    </ul>
  </div>
  <!-- end viewport pc-->
</header>
<div class="header-space">

</div>