ngorgeous/applications/destinos/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from . import views

app_name="destinos_app"

urlpatterns = [
    #url para formulario de contacto
    url(r'^visita-lugares-en-cusco-arequipa-puno-y-todo-el-peru/$',
        views.DestinationListView.as_view(),
        name='destinos_index'
    ),
    #url para ver el detalle de un destino
    url(r'^destinos/(?P<city>[-\w]+)/(?P<slug>[-\w]+)/$',
        views.DestinationDetailView.as_view(),
        name='destinos_detail'
    ),
]

ngorgeous/applications/paquetes/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from . import views

app_name="paquetes_app"

urlpatterns = [
    #url para formulario de contacto
    url(r'^tours-y-paquetes-turisticos-por-cusco-puno-arequipa-peru/$',
        views.FilterPackageView.as_view(),
        name='paquetes_list'
    ),
    #url para ver el detalle de un tour
    url(r'^(?P<city>[-\w]+)/(?P<slug>[-\w]+)/$',
        views.PackageDetailView.as_view(),
        name='paquetes-detail'
    ),
]

ngorgeous/ngorgeous/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
#
#from django.contrib.sitemaps.views import sitemap

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #
    url(r'^', include('applications.home.urls')),
    #urls para aplicacion paquetes
    url(r'^', include('applications.paquetes.urls')),
    #urls para aplicacion destinos
    url(r'^', include('applications.destinos.urls')),
    #urls para aplicacion experiecnias
    url(r'^', include('applications.experiencias.urls')),
    #url for ckeditor
    url(r'^froala_editor/', include('froala_editor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ngorgeous/applications/paquetes/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.template.defaultfilters import slugify
#third import
from datetime import datetime, timedelta
from model_utils.models import TimeStampedModel
#import manager
from .managers import PackageManager, RouteManager, PropertyManager


@python_2_unicode_compatible
class Package(TimeStampedModel):
    """ modelo para paquetes y tours """

    TYPE_CHOICES = (
        ('0', 'Tour'),
        ('1', 'Paquete'),
    )
    name = models.CharField('nombre', max_length=100)
    slogan = models.CharField('Frase', max_length=100)
    image = models.ImageField('imagen', upload_to="paquetes")
    resume = models.TextField('resumen')
    days = models.IntegerField('dias')
    visit = models.IntegerField('visita', default=0)
    short_description = models.TextField('descripcion corta')
    price = models.IntegerField('precio')
    city_origin = models.CharField('Ciudad origen', max_length=100, blank=True)
    city_destination = models.CharField('Ciudad destino', max_length=100, blank=True)
    tags = models.ManyToManyField('miscelanea.Tag', blank=True)
    published = models.BooleanField('Publicado', default=False)
    tipo = models.CharField('Tipo', max_length=1, choices=TYPE_CHOICES)
    slug = models.SlugField(editable=False, max_length=200)
    objects = PackageManager()

    class Meta:
        verbose_name = 'paquete turistico'
        verbose_name_plural = 'paquetes turisticos'
        ordering = ['-created']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.id:
            # calculamos el total de segundos de la hora actual
            now = datetime.now()
            total_time = timedelta(
                hours=now.hour,
                minutes=now.minute,
                seconds=now.second
            )
            seconds = int(total_time.total_seconds())
            slug_unique = '%s %s' % (self.name, str(seconds))
        else:
            seconds = self.slug.split('-')[-1]  # recuperamos los segundos
            slug_unique = '%s %s' % (self.name, str(seconds))

        self.slug = slugify(slug_unique)
        super(Package, self).save(*args, **kwargs)



@python_2_unicode_compatible
class Route(TimeStampedModel):

    order = models.IntegerField(default=0)
    package = models.ForeignKey(
        Package,
        verbose_name='paquete_turistico',
        on_delete=models.CASCADE,
    )
    destination = models.ForeignKey(
        'destinos.Destination',
        verbose_name='destino',
        blank=True,
        null=True,
        on_delete=models.CASCADE,
    )
    #
    objects = RouteManager()

    class Meta:
        verbose_name = 'ruta'
        verbose_name_plural = 'rutas'
        ordering = ['-created']

    def __str__(self):
        return str(self.destination.name) + '---' + str(self.package.name)



@python_2_unicode_compatible
class Property(TimeStampedModel):

    order = models.IntegerField('orden')
    contenido = models.CharField(blank=True, max_length=120)
    route = models.ForeignKey(
        Route,
        verbose_name='rutas',
        on_delete=models.CASCADE,
    )
    #
    objects = PropertyManager()

    class Meta:
        verbose_name = 'propiedad'
        verbose_name_plural = 'propiedades'
        ordering = ['-created']

    def __str__(self):
        return str(self.order)

ngorgeous/applications/paquetes/forms.py
# -*- coding: utf-8 -*-
from django import forms

#
class SearchForm(forms.Form):
   '''
   formulario para buscar paquetes
   '''

   destino1 = forms.CharField(
       max_length='100',
       required=False,
       widget=forms.TextInput(
           attrs={
                'class':'tours__banner__copy__ctrls__form__input',
                'placeholder': 'Origen'
           }
       )
   )
   destino2 = forms.CharField(
       max_length='100',
       required=False,
       widget=forms.TextInput(
           attrs={
                'class':'tours__banner__copy__ctrls__form__input',
                'placeholder': 'Destino'
           }
       )
   )

ngorgeous/applications/paquetes/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.urls import reverse_lazy, reverse

from django.views.generic import (
    CreateView,
    UpdateView,
    TemplateView,
    DeleteView,
    DetailView,
    FormView,
    ListView
)

from django.views.generic.edit import FormMixin

#
from .models import Package, Property, Route
#
from .forms import SearchForm
#
from .functions import rutas_por_paquete

#vistas para blog
class FilterPackageView(ListView):
    """ filtro para Package"""

    context_object_name = 'paquetes'
    template_name = 'paquetes/list.html'

    def get_context_data(self, **kwargs):
        context = super(FilterPackageView, self).get_context_data(**kwargs)
        context['form'] = SearchForm
        return context

    def get_queryset(self):
        #recuperamos el valor por GET
        q = self.request.GET.get("destino1", '')
        r = self.request.GET.get("destino2", '')
        queryset = Package.objects.search_package(q, r)
        return queryset


class PackageDetailView(DetailView):
    model = Package
    template_name = 'paquetes/detail.html'

    def get_context_data(self, **kwargs):
        context = super(PackageDetailView, self).get_context_data(**kwargs)
        context['rutas'] = rutas_por_paquete(self.get_object().pk)
        context['paquetes'] = Package.objects.list_feature()
        return context

ngorgeous/templates/paquetes/base_paquetes.html
{% extends "base.html" %}

{% load  staticfiles %}

{% block css %}
  <meta property="og:type" content="website">
  <meta property="og:locale" content="es_PE">
  <meta property="og:site_name" content="Guia por machu picchu y huayna picchu">
  <meta property="og:url" content="http://gorgeousmachupicchu.com/">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">

{% endblock css %}

{% block js %}
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/foundation.min.js' %}"></script>
  <script src="{% static 'js/app.js' %}"></script>
  <script src="{% static 'js/scrips.js' %}"></script>
{% endblock js %}

ngorgeous/templates/paquetes/detail.html
{% extends "paquetes/base_paquetes.html" %}

{% load  staticfiles %}

{% load thumbnail %}

{% load l10n %}

{% block title %} {{object.name}} {% endblock %}

{% block description %}{{object.short_description}}{% endblock %}

{% block title_rs %}{{object.name}}{% endblock %}

{% block description_rs %}{{object.short_description}}{% endblock %}

{% block tags %}{% for tag in object.tags.all %}{{tag}},{% endfor %} {% endblock tags %}


{% block content %}
  {% include "include/header.html" %}
    <div class="tour-detail">
      <div class="tour-detail__banner">
        <img src="{{package.image.url}}" alt="{{package.name}}" class="tour-detail__banner__img">
        <div class="tour-detail__banner__resume">
          <h3 class="tour-detail__banner__resume__title">{{package.name}}</h3>
          <p class="tour-detail__banner__resume__text">{{package.resume}}</p>
          <p class="tour-detail__banner__resume__price">$ {{package.price}}</p>
        </div>
      </div>

      <div class="grid-container grid-x">
        <h1 class="cell tour-detail__title">{{package.slogan}}</h1>
        <div class="cell small-12 medium-12 large-8 grid-x align-center tour-detail__destinos">
          <h3 class="tour-detail__destinos__title">Conoce estos destinos con este {{package.get_tipo_display}} :</h3>
          {% for r in rutas  %}
            <div class="cell small-12 medium-10 large-12 grid-x tour-detail__destinos__item">
              <div class="cell small-12 medium-6 large-5 tour-detail__destino">
                <img src="{{r.route.destination.image.url}}" alt="{{r.route.destination.name}}" class="tour-detail__destino__img">
              </div>
              <div class="cell small-12 medium-6 large-7 tour-detail__destino">
                <div class="tour-detail__destino__resume">
                  <a href="{% url 'destinos_app:destinos_detail' r.route.destination.city r.route.destination.slug %}" class="tour-detail__destino__resume__name">{{r.route.destination.name}}</a>
                  <span class="tour-detail__leyend">Itinerario</span>
                  <div class="tour-detail__destino__resume__items">
                    {% for i in r.propiedades  %}
                      <div class="tour-detail__destino__resume__items__item">
                        <i class="fa fa-check-circle-o tour-detail__destino__resume__items__item__icon" aria-hidden="true"></i>
                        <p class="tour-detail__destino__resume__items__item__text">{{i.contenido}}</p>
                      </div>
                    {% endfor %}
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
        <div class="cell small-12 medium-12 large-3 grid-x align-center  tour-detail__relacionados">
          <p class="cell tour-detail__relacionados__title">Tours más populares</p>
          {% for p in paquetes %}
            <div class="cell small-12 medium-5 large-12 tour-detail__relacionados__item">
              <img src="{{p.image.url}}" alt="p.name" class="tour-detail__relacionados__item__img">
              <div class="tour-detail__relacionados__item__content">
                <a href="{% url 'paquetes_app:paquetes-detail' p.city_origin p.slug %}" class="tour-detail__relacionados__item__content__title">{{p.name}}</a>
                <p class="tour-detail__relacionados__item__content__days">{{p.days}} dias</p>
                <p class="tour-detail__relacionados__item__content__price">$. {{p.price}}</p>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  {% include "include/footer.html" %}
{% endblock %}

ngorgeous/templates/paquetes/list.html
{% extends "paquetes/base_paquetes.html" %}

{% load  staticfiles %}

{% load thumbnail %}

{% load l10n %}

{% block title %} huayna picchu hike | visita machupichu viaja por el cusco y todo el Perú{% endblock %}

{% block description %}huayna picchu mountain: encuentra tours y paquetes turiscos para conocer el cusco, valle sagrado, puno, arequipa y todo el Perú.{% endblock %}

{% block title_rs %}huayna picchu mountain: encuentra tours y paquetes turiscos para conocer el Perú.{% endblock %}

{% block description_rs %}huayna picchu mountain: encuentra tours y paquetes turiscos para conocer el Perú.{% endblock %}


{% block content %}
  {% include "include/header.html" %}

  <div class="tours">
    <div class="tours__banner">
      <img src="{% static 'img/fondo2.jpg' %}" alt="machupicchu" class="tours__banner__img">
      <div class="tours__banner__copy">
        <div class="tours__banner__copy__content">
          <p class="tours__banner__copy__content__text">Visita todas las maravillas del Perú</p>
          <h1 class="tours__banner__copy__content__h1">Encuentra el tour ideal para ti por todo el Perú.</h1>
        </div>
        <div class="tours__banner__copy__ctrls">
          <span class="tours__banner__copy__ctrls__description">Destinos: </span>
          <form class="tours__banner__copy__ctrls__form" method="get">{% csrf_token %}
            {{form.destino1}}
            {{form.destino2}}
            <button type="submit" class="btn_search">Buscar</button>
          </form>
        </div>
      </div>
    </div>
    <div class="tours__copy">
      <h2 class="tours__copy__title">Tours más populares</h2>
      <p class="tours__copy__description">Disfruta una experiencia inolvidable, por todo el peru con estos fantasticos tours por machu pichu, Nasca y todo el Perú.</p>
    </div>
    <div class="tours__filter">
      <a href="#" class="tours__filter__item">Todo</a>
      <a href="#" class="tours__filter__item">Por Precio</a>
      <a href="#" class="tours__filter__item">Por Dias</a>
    </div>

    <div class="grid-container">
      <div class="tours__cards grid-x grid-margin-x align-center">
        {% for p in paquetes %}
          <div class="cell small-10 medium-6 large-4 aventure__card">
            <img src="{{ p.image.url }}" alt="{{p.name}}" class="aventure__card__img">
            <div class="aventure__card__info">
              <div class="aventure__card__info__main">
                <a href="{% url 'paquetes_app:paquetes-detail' p.city_origin p.slug %}" class="aventure__card__info__main__title" title="{{p.name}}">{{p.name|truncatechars_html:40}}</a>
                <span class="aventure__card__info__main__price">$ {{p.price}}</span>
              </div>
              <div class="aventure__card__info__content">
                <p class="aventure__card__info__content__tag">
                  <i class="fa fa-calendar aventure__card__info__content__tag__icon" aria-hidden="true"></i>
                  <span class="aventure__card__info__content__tag__text">{{p.days}} Dia(s)</span>
                </p>
                <p class="aventure__card__info__content__text" title="{{p.short_description}}">
                  {{p.short_description|truncatechars_html:105}}
                </p>
              </div>
              <div class="aventure__card__info__footer">
                <div class="aventure__card__info__footer__item">
                  <i class="fa fa-circle-o aventure__card__info__footer__item__icon" aria-hidden="true"></i>
                  <span class="aventure__card__info__footer__item__text">{{p.city_origin}}</span>
                </div>
                <div class="aventure__card__info__footer__item">
                  <i class="fa fa-circle aventure__card__info__footer__item__icon" aria-hidden="true"></i>
                  <span class="aventure__card__info__footer__item__text">{{p.city_destination}}</span>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
  {% include "include/footer.html" %}
{% endblock %}