ngorgeous/applications/experiencias/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from . import views

app_name="experiencias_app"

urlpatterns = [
    #url para formulario de contacto
    url(r'^viaje-por-el-peru-con-experiencias-inolvidables/$',
        views.ExperienceListView.as_view(),
        name='experiencias_index'
    ),
    #url para ver el detalle de un destino
    url(r'^viajes-por-peru/(?P<slug>[-\w]+)/(?P<pk>\d+)/$',
        views.ExperienceDetailView.as_view(),
        name='experiencias_detail'
    ),
]

ngorgeous/applications/paquetes/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from . import views

app_name="paquetes_app"

urlpatterns = [
    #url para formulario de contacto
    url(r'^tours-y-paquetes-turisticos-por-cusco-puno-arequipa-peru/$',
        views.FilterPackageView.as_view(),
        name='paquetes_list'
    ),
    #url para ver el detalle de un tour
    url(r'^(?P<city>[-\w]+)/(?P<slug>[-\w]+)/$',
        views.PackageDetailView.as_view(),
        name='paquetes-detail'
    ),
]

ngorgeous/ngorgeous/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
#
#from django.contrib.sitemaps.views import sitemap

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #
    url(r'^', include('applications.home.urls')),
    #urls para aplicacion paquetes
    url(r'^', include('applications.paquetes.urls')),
    #urls para aplicacion destinos
    url(r'^', include('applications.destinos.urls')),
    #urls para aplicacion experiecnias
    url(r'^', include('applications.experiencias.urls')),
    #url for ckeditor
    url(r'^froala_editor/', include('froala_editor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ngorgeous/applications/experiencias/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.template.defaultfilters import slugify
#third library
from froala_editor.fields import FroalaField
from model_utils.models import TimeStampedModel
from datetime import datetime, timedelta


@python_2_unicode_compatible
class Experience(TimeStampedModel):

    name = models.CharField('nombre', max_length=100)
    image = models.ImageField('foto', upload_to="experiencia")
    video = models.URLField('video', blank=True)
    guide = models.ForeignKey(
        'miscelanea.Guide',
        verbose_name='guia',
        null=True,
        blank=True,
        on_delete=models.CASCADE,
    )
    short_description = models.TextField('Descripcion', blank=True)
    guide_experience = FroalaField()
    published = models.BooleanField('Publicado', default=True)
    slug = models.SlugField(editable=False, max_length=200)
    tags = models.ManyToManyField('miscelanea.Tag')

    class Meta:

        verbose_name = 'Experiencia'
        verbose_name_plural = 'Experiencias'
        ordering = ['-created']

    def __str__(self):

        return self.name


    def save(self, *args, **kwargs):
        if not self.id:
            # calculamos el total de segundos de la hora actual
            now = datetime.now()
            total_time = timedelta(
                hours=now.hour,
                minutes=now.minute,
                seconds=now.second
            )
            seconds = int(total_time.total_seconds())
            slug_unique = '%s %s' % (self.name, str(seconds))
        else:
            seconds = self.slug.split('-')[-1]  # recuperamos los segundos
            slug_unique = '%s %s' % (self.name, str(seconds))

        self.slug = slugify(slug_unique)
        super(Experience, self).save(*args, **kwargs)

ngorgeous/applications/experiencias/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.urls import reverse_lazy, reverse

from django.views.generic import (
    CreateView,
    UpdateView,
    TemplateView,
    DeleteView,
    DetailView,
    FormView,
    ListView
)

#app paquete
from applications.paquetes.models import Package
#
from .models import Experience

#vistas para blog
class ExperienceListView(ListView):
    """ Lista las experiencias del guia"""

    context_object_name = 'experiencias'
    template_name = 'experiencias/index.html'

    def get_queryset(self):
        queryset = Experience.objects.filter(
            published=True
        ).order_by('-created')[:30]
        return queryset


class ExperienceDetailView(DetailView):
    model = Experience
    template_name = 'experiencias/detail.html'

    def get_context_data(self, **kwargs):
        context = super(ExperienceDetailView, self).get_context_data(**kwargs)
        context['paquetes'] = Package.objects.list_feature()
        return context

ngorgeous/templates/experiencias/base_experiencias.html
{% extends "base.html" %}

{% load  staticfiles %}

{% block css %}
  <meta property="og:type" content="website">
  <meta property="og:locale" content="es_PE">
  <meta property="og:site_name" content="Guia por machu picchu y huayna picchu">
  <meta property="og:url" content="http://gorgeousmachupicchu.com/">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">

{% endblock css %}

{% block js %}
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/foundation.min.js' %}"></script>
  <script src="{% static 'js/app.js' %}"></script>
  <script src="{% static 'js/scrips.js' %}"></script>

{% endblock js %}

ngorgeous/templates/experiencias/detail.html
{% extends "destinos/base_destinos.html" %}

{% load  staticfiles %}

{% load thumbnail %}

{% load l10n %}

{% block title %} {{object.name}} {% endblock %}

{% block description %}{{object.short_description}}{% endblock %}

{% block title_rs %}{{object.name}}{% endblock %}

{% block description_rs %}{{object.short_description}}{% endblock %}

{% block tags %}{% for tag in object.tags.all %}{{tag}},{% endfor %} {% endblock tags %}


{% block content %}
  {% include "include/header.html" %}
    <div class="grid-container">
      <div class="grid-x grid-margin-x blog">
        <h1 class="cell blog__title">{{object.name}}</h1>
        <p class="cell blog__etiqueta">@{{object.guide.name}}</p>
        <img src="{{object.image.url}}" alt="{{object.name}}" class="blog__img">

        <div class="cell small-12 medium-12 large-8 blog__content">
          <p class="blog__content__text">
            {{object.guide_experience|safe}}
          </p>
        </div>
        <div class="cell small-12 medium-12 large-4 blog__relations">
          <h1 class="cell blog__relations__title">Sugeridos:</h1>
          {% for p in paquetes  %}
            <div class="blog__relations__card">
              <img src="{{p.image.url}}" alt="name" class="blog__relations__card__img">
              <div class="blog__relations__card__content">
                <a href="{% url 'paquetes_app:paquetes-detail' p.city_origin p.slug %}" class="blog__relations__card__content__title">{{p.name}}</a>
                <span class="blog__relations__card__content__label1">{{p.days}}</span>
                <p class="blog__relations__card__content__label2">$. {{p.price}}</p>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  {% include "include/footer.html" %}
{% endblock %}

ngorgeous/templates/experiencias/index.html
{% extends "destinos/base_destinos.html" %}

{% load  staticfiles %}

{% load thumbnail %}

{% load l10n %}

{% block title %} huayna picchu hike | Viajes por Peru {% endblock %}

{% block description %}huayna picchu, Machu Picchu| nuestros viajes por el Peru. arequipa, Cusco, Puno.{% endblock %}

{% block title_rs %}Viaja Por Peru {% endblock %}

{% block description_rs %}Nuestros viajes por el Peru. arequipa, Cusco, Puno. | huayna picchu, Machu Picchu{% endblock %}


{% block content %}
  {% include "include/header.html" %}
    <div class="grid-container experiencies">
      <h1 class="experiencies__title">Nuestras experiecias en distintos lugares del Perú</h1>
      <p class="experiencies__description">Hemos podido visitar distintos lugares del Perú, con maravillosos grupos de personas, revisa nuestras experiencias.</p>
      <div class="grid-x grid-margin-x align-center">
        {% for e in experiencias %}
          <div class="cell small-12 medium-6">
            <div class="experiencie__card">
              <div class="experiencie__card__img">
                <img src="{{e.image.url}}" alt="name" class="experiencie__card__img__imagen">
              </div>
              <div class="experiencie__card__content">
                <h3 class="experiencie__card__content__title">{{e.name}}</h3>
                <span class="experiencie__card__content__date">{{e.created}}</span>
                <p class="experiencie__card__content__text">{{e.short_description|truncatechars_html:100}}</p>
                <a href="{% url 'experiencias_app:experiencias_detail' e.slug e.pk %}" class="experiencie__card__content__a">Ver más</a>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  {% include "include/footer.html" %}
{% endblock %}